export type EmojiItem = {
  emoji: string;
  name: string;
  category: string;
};

export const EMOJI_CATEGORIES = [
  "Smileys",
  "Gestures",
  "Hearts",
  "Animals",
  "Food",
  "Travel",
  "Objects",
  "Symbols",
] as const;

export const COMMON_EMOJIS: EmojiItem[] = [
  { emoji: "😀", name: "grinning face", category: "Smileys" },
  { emoji: "😃", name: "grinning face big eyes", category: "Smileys" },
  { emoji: "😄", name: "grinning face smiling eyes", category: "Smileys" },
  { emoji: "😁", name: "beaming face", category: "Smileys" },
  { emoji: "😅", name: "grinning sweat", category: "Smileys" },
  { emoji: "😂", name: "face tears of joy", category: "Smileys" },
  { emoji: "🤣", name: "rolling on floor laughing", category: "Smileys" },
  { emoji: "😊", name: "smiling eyes", category: "Smileys" },
  { emoji: "😇", name: "smiling halo", category: "Smileys" },
  { emoji: "🙂", name: "slightly smiling", category: "Smileys" },
  { emoji: "😉", name: "winking face", category: "Smileys" },
  { emoji: "😍", name: "heart eyes", category: "Smileys" },
  { emoji: "🥰", name: "smiling hearts", category: "Smileys" },
  { emoji: "😘", name: "face blowing kiss", category: "Smileys" },
  { emoji: "😗", name: "kissing face", category: "Smileys" },
  { emoji: "😋", name: "face savoring food", category: "Smileys" },
  { emoji: "😛", name: "face tongue", category: "Smileys" },
  { emoji: "😜", name: "winking tongue", category: "Smileys" },
  { emoji: "🤪", name: "zany face", category: "Smileys" },
  { emoji: "😝", name: "squinting tongue", category: "Smileys" },
  { emoji: "🤑", name: "money mouth", category: "Smileys" },
  { emoji: "🤗", name: "hugging face", category: "Smileys" },
  { emoji: "🤭", name: "hand over mouth", category: "Smileys" },
  { emoji: "🤫", name: "shushing face", category: "Smileys" },
  { emoji: "🤔", name: "thinking face", category: "Smileys" },
  { emoji: "😐", name: "neutral face", category: "Smileys" },
  { emoji: "😑", name: "expressionless", category: "Smileys" },
  { emoji: "😶", name: "no mouth", category: "Smileys" },
  { emoji: "😏", name: "smirking face", category: "Smileys" },
  { emoji: "😒", name: "unamused", category: "Smileys" },
  { emoji: "🙄", name: "rolling eyes", category: "Smileys" },
  { emoji: "😬", name: "grimacing", category: "Smileys" },
  { emoji: "😌", name: "relieved", category: "Smileys" },
  { emoji: "😔", name: "pensive", category: "Smileys" },
  { emoji: "😪", name: "sleepy", category: "Smileys" },
  { emoji: "🤤", name: "drooling", category: "Smileys" },
  { emoji: "😴", name: "sleeping", category: "Smileys" },
  { emoji: "😷", name: "medical mask", category: "Smileys" },
  { emoji: "🤒", name: "thermometer face", category: "Smileys" },
  { emoji: "🤕", name: "head bandage", category: "Smileys" },
  { emoji: "🤢", name: "nauseated", category: "Smileys" },
  { emoji: "🤮", name: "vomiting", category: "Smileys" },
  { emoji: "🤧", name: "sneezing", category: "Smileys" },
  { emoji: "🥵", name: "hot face", category: "Smileys" },
  { emoji: "🥶", name: "cold face", category: "Smileys" },
  { emoji: "🥴", name: "woozy", category: "Smileys" },
  { emoji: "😵", name: "dizzy face", category: "Smileys" },
  { emoji: "🤯", name: "exploding head", category: "Smileys" },
  { emoji: "🤠", name: "cowboy hat", category: "Smileys" },
  { emoji: "🥳", name: "partying face", category: "Smileys" },
  { emoji: "😎", name: "sunglasses", category: "Smileys" },
  { emoji: "🤓", name: "nerd face", category: "Smileys" },
  { emoji: "😕", name: "confused", category: "Smileys" },
  { emoji: "😟", name: "worried", category: "Smileys" },
  { emoji: "🙁", name: "slightly frowning", category: "Smileys" },
  { emoji: "☹️", name: "frowning", category: "Smileys" },
  { emoji: "😮", name: "open mouth", category: "Smileys" },
  { emoji: "😯", name: "hushed", category: "Smileys" },
  { emoji: "😲", name: "astonished", category: "Smileys" },
  { emoji: "😳", name: "flushed", category: "Smileys" },
  { emoji: "🥺", name: "pleading", category: "Smileys" },
  { emoji: "😦", name: "frowning open mouth", category: "Smileys" },
  { emoji: "😧", name: "anguished", category: "Smileys" },
  { emoji: "😨", name: "fearful", category: "Smileys" },
  { emoji: "😰", name: "anxious sweat", category: "Smileys" },
  { emoji: "😥", name: "sad relieved", category: "Smileys" },
  { emoji: "😢", name: "crying", category: "Smileys" },
  { emoji: "😭", name: "loudly crying", category: "Smileys" },
  { emoji: "😱", name: "screaming fear", category: "Smileys" },
  { emoji: "😖", name: "confounded", category: "Smileys" },
  { emoji: "😣", name: "persevering", category: "Smileys" },
  { emoji: "😞", name: "disappointed", category: "Smileys" },
  { emoji: "😓", name: "downcast sweat", category: "Smileys" },
  { emoji: "😩", name: "weary", category: "Smileys" },
  { emoji: "😫", name: "tired", category: "Smileys" },
  { emoji: "😤", name: "steam nose", category: "Smileys" },
  { emoji: "😡", name: "pouting", category: "Smileys" },
  { emoji: "😠", name: "angry", category: "Smileys" },
  { emoji: "🤬", name: "swearing", category: "Smileys" },
  { emoji: "👍", name: "thumbs up", category: "Gestures" },
  { emoji: "👎", name: "thumbs down", category: "Gestures" },
  { emoji: "👌", name: "ok hand", category: "Gestures" },
  { emoji: "✌️", name: "victory hand", category: "Gestures" },
  { emoji: "🤞", name: "crossed fingers", category: "Gestures" },
  { emoji: "🤟", name: "love you gesture", category: "Gestures" },
  { emoji: "🤘", name: "horns", category: "Gestures" },
  { emoji: "🤙", name: "call me hand", category: "Gestures" },
  { emoji: "👋", name: "waving hand", category: "Gestures" },
  { emoji: "🤚", name: "raised back hand", category: "Gestures" },
  { emoji: "🖐️", name: "hand fingers splayed", category: "Gestures" },
  { emoji: "✋", name: "raised hand", category: "Gestures" },
  { emoji: "🖖", name: "vulcan salute", category: "Gestures" },
  { emoji: "👏", name: "clapping hands", category: "Gestures" },
  { emoji: "🙌", name: "raising hands", category: "Gestures" },
  { emoji: "👐", name: "open hands", category: "Gestures" },
  { emoji: "🤲", name: "palms up", category: "Gestures" },
  { emoji: "🤝", name: "handshake", category: "Gestures" },
  { emoji: "🙏", name: "folded hands", category: "Gestures" },
  { emoji: "💪", name: "flexed biceps", category: "Gestures" },
  { emoji: "❤️", name: "red heart", category: "Hearts" },
  { emoji: "🧡", name: "orange heart", category: "Hearts" },
  { emoji: "💛", name: "yellow heart", category: "Hearts" },
  { emoji: "💚", name: "green heart", category: "Hearts" },
  { emoji: "💙", name: "blue heart", category: "Hearts" },
  { emoji: "💜", name: "purple heart", category: "Hearts" },
  { emoji: "🖤", name: "black heart", category: "Hearts" },
  { emoji: "🤍", name: "white heart", category: "Hearts" },
  { emoji: "💔", name: "broken heart", category: "Hearts" },
  { emoji: "💕", name: "two hearts", category: "Hearts" },
  { emoji: "💞", name: "revolving hearts", category: "Hearts" },
  { emoji: "💓", name: "beating heart", category: "Hearts" },
  { emoji: "💗", name: "growing heart", category: "Hearts" },
  { emoji: "💖", name: "sparkling heart", category: "Hearts" },
  { emoji: "💘", name: "heart arrow", category: "Hearts" },
  { emoji: "💝", name: "heart ribbon", category: "Hearts" },
  { emoji: "🐶", name: "dog", category: "Animals" },
  { emoji: "🐱", name: "cat", category: "Animals" },
  { emoji: "🐭", name: "mouse", category: "Animals" },
  { emoji: "🐹", name: "hamster", category: "Animals" },
  { emoji: "🐰", name: "rabbit", category: "Animals" },
  { emoji: "🦊", name: "fox", category: "Animals" },
  { emoji: "🐻", name: "bear", category: "Animals" },
  { emoji: "🐼", name: "panda", category: "Animals" },
  { emoji: "🐨", name: "koala", category: "Animals" },
  { emoji: "🐯", name: "tiger", category: "Animals" },
  { emoji: "🦁", name: "lion", category: "Animals" },
  { emoji: "🐮", name: "cow", category: "Animals" },
  { emoji: "🐷", name: "pig", category: "Animals" },
  { emoji: "🐸", name: "frog", category: "Animals" },
  { emoji: "🐵", name: "monkey", category: "Animals" },
  { emoji: "🐔", name: "chicken", category: "Animals" },
  { emoji: "🐧", name: "penguin", category: "Animals" },
  { emoji: "🐦", name: "bird", category: "Animals" },
  { emoji: "🦄", name: "unicorn", category: "Animals" },
  { emoji: "🐝", name: "bee", category: "Animals" },
  { emoji: "🍎", name: "apple", category: "Food" },
  { emoji: "🍊", name: "orange", category: "Food" },
  { emoji: "🍋", name: "lemon", category: "Food" },
  { emoji: "🍌", name: "banana", category: "Food" },
  { emoji: "🍉", name: "watermelon", category: "Food" },
  { emoji: "🍇", name: "grapes", category: "Food" },
  { emoji: "🍓", name: "strawberry", category: "Food" },
  { emoji: "🍒", name: "cherries", category: "Food" },
  { emoji: "🍑", name: "peach", category: "Food" },
  { emoji: "🍍", name: "pineapple", category: "Food" },
  { emoji: "🥭", name: "mango", category: "Food" },
  { emoji: "🍔", name: "hamburger", category: "Food" },
  { emoji: "🍟", name: "fries", category: "Food" },
  { emoji: "🍕", name: "pizza", category: "Food" },
  { emoji: "🌭", name: "hot dog", category: "Food" },
  { emoji: "🍿", name: "popcorn", category: "Food" },
  { emoji: "🧁", name: "cupcake", category: "Food" },
  { emoji: "🍰", name: "cake", category: "Food" },
  { emoji: "🎂", name: "birthday cake", category: "Food" },
  { emoji: "☕", name: "coffee", category: "Food" },
  { emoji: "🍵", name: "tea", category: "Food" },
  { emoji: "🍺", name: "beer", category: "Food" },
  { emoji: "🍷", name: "wine", category: "Food" },
  { emoji: "🚗", name: "car", category: "Travel" },
  { emoji: "🚕", name: "taxi", category: "Travel" },
  { emoji: "🚌", name: "bus", category: "Travel" },
  { emoji: "✈️", name: "airplane", category: "Travel" },
  { emoji: "🚀", name: "rocket", category: "Travel" },
  { emoji: "🛸", name: "ufo", category: "Travel" },
  { emoji: "🚢", name: "ship", category: "Travel" },
  { emoji: "⛵", name: "sailboat", category: "Travel" },
  { emoji: "🏠", name: "house", category: "Travel" },
  { emoji: "🏢", name: "office", category: "Travel" },
  { emoji: "🌍", name: "earth", category: "Travel" },
  { emoji: "🌙", name: "moon", category: "Travel" },
  { emoji: "⭐", name: "star", category: "Travel" },
  { emoji: "🌈", name: "rainbow", category: "Travel" },
  { emoji: "☀️", name: "sun", category: "Travel" },
  { emoji: "🌧️", name: "rain", category: "Travel" },
  { emoji: "❄️", name: "snowflake", category: "Travel" },
  { emoji: "💡", name: "light bulb", category: "Objects" },
  { emoji: "📱", name: "mobile phone", category: "Objects" },
  { emoji: "💻", name: "laptop", category: "Objects" },
  { emoji: "⌚", name: "watch", category: "Objects" },
  { emoji: "📷", name: "camera", category: "Objects" },
  { emoji: "🎵", name: "music note", category: "Objects" },
  { emoji: "🎶", name: "music notes", category: "Objects" },
  { emoji: "🎁", name: "gift", category: "Objects" },
  { emoji: "🎈", name: "balloon", category: "Objects" },
  { emoji: "🎉", name: "party popper", category: "Objects" },
  { emoji: "🏆", name: "trophy", category: "Objects" },
  { emoji: "⚽", name: "soccer", category: "Objects" },
  { emoji: "🏀", name: "basketball", category: "Objects" },
  { emoji: "🎯", name: "dart", category: "Objects" },
  { emoji: "🔔", name: "bell", category: "Objects" },
  { emoji: "🔑", name: "key", category: "Objects" },
  { emoji: "✅", name: "check mark", category: "Symbols" },
  { emoji: "❌", name: "cross mark", category: "Symbols" },
  { emoji: "❓", name: "question mark", category: "Symbols" },
  { emoji: "❗", name: "exclamation mark", category: "Symbols" },
  { emoji: "💯", name: "hundred points", category: "Symbols" },
  { emoji: "🔥", name: "fire", category: "Symbols" },
  { emoji: "✨", name: "sparkles", category: "Symbols" },
  { emoji: "💫", name: "dizzy", category: "Symbols" },
  { emoji: "⚡", name: "lightning", category: "Symbols" },
  { emoji: "💥", name: "collision", category: "Symbols" },
  { emoji: "🎵", name: "musical note", category: "Symbols" },
];
